<?php

namespace App\Exceptions;

class ErrorCode
{
    const AI_RATE_LIMIT = 'AI_RATE_LIMIT';
    const AI_TIMEOUT = 'AI_TIMEOUT';
    const AI_UNAVAILABLE = 'AI_UNAVAILABLE';
    const AI_INVALID_RESPONSE = 'AI_INVALID_RESPONSE';
    const AI_CONFIGURATION = 'AI_CONFIGURATION';
    const AI_CONTENT_FILTERED = 'AI_CONTENT_FILTERED';
    const AI_CIRCUIT_OPEN = 'AI_CIRCUIT_OPEN';
    const AI_ANALYSIS_FAILED = 'AI_ANALYSIS_FAILED';

    const DB_QUERY_FAILED = 'DB_QUERY_FAILED';
    const DB_DEADLOCK = 'DB_DEADLOCK';
    const DB_CONNECTION_LOST = 'DB_CONNECTION_LOST';

    const QUEUE_FAILED = 'QUEUE_FAILED';
    const QUEUE_MAX_RETRIES = 'QUEUE_MAX_RETRIES';
    const QUEUE_CONNECTION = 'QUEUE_CONNECTION';

    const TICKET_NOT_FOUND = 'TICKET_NOT_FOUND';
    const TICKET_CLOSED = 'TICKET_CLOSED';
    const TICKET_SAME_STATUS = 'TICKET_SAME_STATUS';
    const TICKET_INVALID_TRANSITION = 'TICKET_INVALID_TRANSITION';

    const VALIDATION_ERROR = 'VALIDATION_ERROR';
    const NOT_FOUND = 'NOT_FOUND';
    const FORBIDDEN = 'FORBIDDEN';
    const UNAUTHORIZED = 'UNAUTHORIZED';
    const SERVER_ERROR = 'SERVER_ERROR';

    const ROUTE_NOT_FOUND = 'ROUTE_NOT_FOUND';
}
